### ISSUE TITLE
Crash with Glide 4.9.0

### ISSUE THREAD

**Issue by DennyWeinberg** [aminography/RedirectGlide#2]
```
    java.lang.NoSuchMethodError: No super method apply(Lcom/bumptech/glide/request/RequestOptions;)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/com.levionsoftware.photo_map_for_google_photos-1LzP879Fxqon4fNvsF92kQ==/base.apk!classes2.dex)
        at com.aminography.redirectglide.GlideOptions.apply(GlideOptions.java:605)
        at com.aminography.redirectglide.GlideRequests.setRequestOptions(GlideRequests.java:170)
        at com.bumptech.glide.RequestManager.<init>(RequestManager.java:136)
        at com.bumptech.glide.RequestManager.<init>(RequestManager.java:94)
        at com.aminography.redirectglide.GlideRequests.<init>(GlideRequests.java:38)
        at com.bumptech.glide.GeneratedRequestManagerFactory.build(GeneratedRequestManagerFactory.java:19)
        at com.bumptech.glide.manager.RequestManagerRetriever.supportFragmentGet(RequestManagerRetriever.java:441)
        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:134)
        at com.bumptech.glide.Glide.with(Glide.java:741)
        at com.aminography.redirectglide.GlideApp.with(GlideApp.java:104)
```

Works with 4.8.0

**Comment by aminography** [comment]
Thank you for informing the problem.
Version 1.0.3 has published which is compatible with Glide 4.9.0.
